### ISSUE TITLE
未登录或登录已经超时

### ISSUE THREAD

**Issue by YueHua46** [Qs315490/YiBan_AutoSgin#12]
## 错误信息：
```
  ⚡Sears ❯❯ py .\yibanAutoSign.py
Exception in thread Thread-1 (start_sign):
Traceback (most recent call last):
  File "C:\Users\Sears\scoop\apps\miniconda3\current\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\Sears\scoop\apps\miniconda3\current\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Sears\Desktop\yiban\YiBan_AutoSgin\src\yibanAutoSign.py", line 13, in start_sign
    time_range=yb.task_feedback.get_sign_task()
  File "C:\Users\Sears\scoop\apps\miniconda3\current\lib\site-packages\yiban\Core\TaskFeedback.py", line 63, in get_sign_task
    raise Exception(f"Get Night Attendance Sign Tasks Error {response['msg']}")
Exception: Get Night Attendance Sign Tasks Error 未登录或登录已经超时
```
这是什么情况啊？按照步骤来的，userData.py也在src里了

**Comment by Qs315490** [comment]
这个问题是fyiban模块报错，应该向fyiban作者反馈
